### ISSUE TITLE
Inaccurate bombs

### ISSUE THREAD

**Issue by BurpDerp** [binji/porklike.gb#10]
In pico 8 version, bombs destroy only cracked walls. In here they destroy regular walls.

In pico 8 version ghosts standing next to you are always visible. In here they can be invisible.

In pico 8 version scorpions blind you for 29 turns. In here 30 turns.

In pico 8 version if you ascend while a monster stands next to stairs, you take no damage. In here a slime hit me.

I have noticed issue #1 too.

You can restart quickly by pressing start in pico version, that would be helpful to have.

Small graphical glitch: if you are at the bottom tile and try to move below, the character sprite flashes.

Thanks for the port, this is fun for gameboy. May i ask why are there inaccuracies, isn't porklike open source?

edit: More bugs

When i stepped on a trap, my character became gray. He should have stayed yellow. I'm playing GBC version.

Throw a bolt to down when you are at the bottom tile. The bolt comes out from other side of the map and hit you.

When you hold down the arrow key, our character stops for a second then continuously move. That stop is slowing the pace.

**Comment by ZackyZzz** [comment]
Another small inaccuracy: Scorpions blind for 29 turns, not 30

**Comment by ZackyZzz** [comment]
![chest](https://github.com/binji/porklike.gb/assets/115259943/837097d5-dbbb-4275-b4b8-7f8ce0ad67dc)
How

**Comment by ZackyZzz** [comment]
![chest](https://github.com/binji/porklike.gb/assets/115259943/d8b8bd37-9577-4028-809d-8fb9a528a9d0)
How do i reach that chest?

**Comment by binji** [comment]
Hey, thanks for the great feedback! I'll take a look at fixing these things soon.

> May i ask why are there inaccuracies, isn't porklike open source?

Sort of, the porklike tutorial is developed on the LazyDev's youtube channel, but the final porklike game (which this is a port of) has a lot of changes that were not included there. However, you are able to extract the Lua code to see the behavior. I just have made a few mistakes in the porting process. :-)

**Comment by ZackyZzz** [comment]
Okay let me report 1 more bug: when i stepped on a trap, my character became gray. He should have stayed yellow. I'm playing GBC version

**Comment by binji** [comment]
OK, took a long time but I think I fixed all of these in v1.0.13 :-D
