### ISSUE TITLE
Porklike in .pocket format

### ISSUE THREAD

**Issue by JoseJX** [binji/porklike.gb#4]
Hi!

I was able to compile and play this game on the Analogue pocket by building for the _pocket_ target. I'm hosting a binary of it [here](http://github.com/JoseJX/analogue-pocket-patches#porklike) after someone requested a .pocket port. I don't think it runs afoul of any license issues but if you'd like to update your itch site to include it or your own build, I will happily remove it.

Thanks for the great work on the game!

**Comment by binji** [comment]
Thanks for adding it @JoseJX! Good point, I should update itch.io :-)

**Comment by binji** [comment]
I added it to the itch.io page (see https://binji.itch.io/porklikegb), feel free to keep it on your page though!
