### ISSUE TITLE
Attacking the scorpions sometimes cause crashes

### ISSUE THREAD

**Issue by SpookySquidGames** [binji/porklike.gb#5]
Have had a situation where attacking a scorpion causes a crash, screen goes white no inputs register till I reboot. Seems to be rare. I'm 
running v1.0.7 .pocket file on an Analogue Pocket, but I think I had this happen once with an earlier version. 

Also had a situation where attacking scorpions did not cause blindness for a long string of scorpion kills. Could be just lucky RNG but it stood out.

**Comment by binji** [comment]
Oh, interesting! I'll take a look and see if I can find a repro.

**Comment by binji** [comment]
I definitely found some bad bugs, but I'm not sure they would explain the screen going white. 
I'll push this up as a new version anyway. Thanks for filing a bug!

I also checked out the random number generator, and it looks like it's possible to get the same 50% chance up to 16 times in a row. Though the random number generator is also pulled for a lot of other reasons too, so I suppose it's possible it could be even more than that, but I'd guess not. In any case, I'd say a really long lucky streak might be a bug, but it's probably just lucky RNG.

**Comment by SpookySquidGames** [comment]
Ok will update to the latest version when I have a chance and let you know if it happens again. Thanks for having a look and pushing an update!

Also yeah if it's a 50/50 chance, my string of good luck probably was just a string of good luck. I wasn't sure what the % chance of scorpions causing blindness was.

**Comment by SpookySquidGames** [comment]
Played a bunch of rounds with the latest version. So far no crashes when attacking scorpions!

**Comment by binji** [comment]
No worries, I think it makes sense to close it out. Feel free to open it back up if you see it again!
