### ISSUE TITLE
How can I build it?

### ISSUE THREAD

**Issue by DunhamGitHub** [binji/porklike.gb#7]
Getting a build error with "make" (vanilla pulled).

* Am I missing "ninja"?

<img width="488" alt="Screenshot 2023-07-22 at 09 03 58" src="https://github.com/binji/porklike.gb/assets/6884752/304e934c-df5e-4237-93be-82d6d27df82a">

**Comment by binji** [comment]
It looks like you don't have gbdk set up. You can find it here: https://github.com/gbdk-2020/gbdk-2020

The build no longer uses ninja, so that isn't the problem

**Comment by DunhamGitHub** [comment]
I downloaded "gbdk" ...is it too _new_?

<img width="488" alt="Screenshot 2023-07-23 at 08 46 28" src="https://github.com/binji/porklike.gb/assets/6884752/0b274f04-ce72-41bc-b0a0-7d544cd5e445">

**Comment by binji** [comment]
Yep, it looks like they changed some stuff in the newest version; it won't just work. I'll take a look at upgrading to latest soon

**Comment by binji** [comment]
Fixed in v1.0.12
