### ISSUE TITLE
.gbc ROM issues with KiGB, mGBA (MacOS)

### ISSUE THREAD

**Issue by DunhamGitHub** [binji/porklike.gb#8]
Does not run on either ...

*Have not yet tested the .gbc on my APocket (the .pocket ROM works there)

<img width="641" alt="Screenshot 2023-07-23 at 08 51 30" src="https://github.com/binji/porklike.gb/assets/6884752/daf2bc8b-cb78-4541-9cb7-86c4e98a98e8">

<img width="640" alt="Screenshot 2023-07-23 at 08 51 44" src="https://github.com/binji/porklike.gb/assets/6884752/ff22188c-c238-44a1-9fcb-3c99656ed3b4">

**Comment by binji** [comment]
Good call, I fixed it in 1.0.10 but broke it again in 1.0.11. Thanks for pointing it out! I'll fix and push out a new version

**Comment by binji** [comment]
Fixed in v1.0.12
